variable location {}
variable resourceGroupName {}
variable storageAccountName {}
variable storageAccountType {}
variable publicIPAddressName {}
variable virtualNetworkName {}
variable virtualNetworkAddressSpace {}
variable subnetName {}
variable subnetAddressPrefix {}
variable networkInterfaceName {}
variable VMName {}
variable VMSize {}
variable imagePublisher {}
variable imageOffer {}
variable imageSKU {}
variable adminUsername {}
variable adminPassword {}
