variable "resourceGroupName" {}
variable "location" {}
variable "name" {}
variable "size" {}
variable "imagePublisher" {}
variable "imageOffer" {}
variable "imageSKU" {}
variable "adminUsername" {}
variable "adminPassword" {}
variable "networkInterfaceID" {}
variable "storageAccountPrimaryBlobEndpoint" {}